steps:
  # Dockerイメージをビルド（タイムアウト時間を延長）
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/sixth-arbor-448303-i3/mimi-app", "."]
    timeout: 1800s # 30分のタイムアウト

  # ビルドしたイメージをContainer Registryにプッシュ
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/sixth-arbor-448303-i3/mimi-app"]

  # Cloud Runにデプロイ
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: gcloud
    args:
      - "run"
      - "deploy"
      - "mimi-app"
      - "--image"
      - "gcr.io/sixth-arbor-448303-i3/mimi-app"
      - "--platform"
      - "managed"
      - "--region"
      - "us-central1"
      - "--allow-unauthenticated"
      - "--memory=2Gi" # メモリを増やす
      - "--cpu=2" # CPUコアを増やす
      - "--port=8080" # ポートを明示的に指定

images:
  - "gcr.io/sixth-arbor-448303-i3/mimi-app"

timeout: 2100s # 全体のビルド時間を35分に設定
