// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBc6Rhg8kdyAZFCOyBJHPAmKHTD3lMuY-I',
    appId: '1:36692564230:web:71f234665092ad6f64e687',
    messagingSenderId: '36692564230',
    projectId: 'sixth-arbor-448303-i3',
    authDomain: 'sixth-arbor-448303-i3.firebaseapp.com',
    storageBucket: 'sixth-arbor-448303-i3.firebasestorage.app',
    measurementId: 'G-PY1CFV9R32',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC-Suib3CPmx0XOyGUDqeliJPlF5SZOHi8',
    appId: '1:36692564230:android:1cce00506de2faa564e687',
    messagingSenderId: '36692564230',
    projectId: 'sixth-arbor-448303-i3',
    storageBucket: 'sixth-arbor-448303-i3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAbwkIKCcAy2W9EIa8VRJpn27NEtuZ6hXI',
    appId: '1:36692564230:ios:65e99c209258f93e64e687',
    messagingSenderId: '36692564230',
    projectId: 'sixth-arbor-448303-i3',
    storageBucket: 'sixth-arbor-448303-i3.firebasestorage.app',
    iosBundleId: 'com.example.mimi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAbwkIKCcAy2W9EIa8VRJpn27NEtuZ6hXI',
    appId: '1:36692564230:ios:65e99c209258f93e64e687',
    messagingSenderId: '36692564230',
    projectId: 'sixth-arbor-448303-i3',
    storageBucket: 'sixth-arbor-448303-i3.firebasestorage.app',
    iosBundleId: 'com.example.mimi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBc6Rhg8kdyAZFCOyBJHPAmKHTD3lMuY-I',
    appId: '1:36692564230:web:6ed9e5d8fecf8e7b64e687',
    messagingSenderId: '36692564230',
    projectId: 'sixth-arbor-448303-i3',
    authDomain: 'sixth-arbor-448303-i3.firebaseapp.com',
    storageBucket: 'sixth-arbor-448303-i3.firebasestorage.app',
    measurementId: 'G-6ZVYRHV102',
  );

}